audio:
  source:
    dir: /work/data
  target:
    dir: digits_audio
data:
  dir: data
  split:
    train: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    test: [9]
  text:
    spk2gender: spk2gender
    wav2scp: wav.scp
egs:
  root: /work/kaldi/egs/digits
