audio:
  source:
    dir: /work/data
  target:
    dir: digits_audio
data:
  dir: data
  split:
    train: [0, 1, 2, 3, 4, 5, 6, 7, 8]
    test: [9]
  text:
    corpus: local/corpus.txt
    lexicon: {src: config/dict/lexicon.txt, tgt: local/dict/lexicon.txt}
    nonsilence_phones: {src: config/dict/nonsilence_phones.txt, tgt: local/dict/nonsilence_phones.txt}
    optional_silence: {src: config/dict/optional_silence.txt, tgt: local/dict/optional_silence.txt}
    silence_phones: {src: config/dict/silence_phones.txt, tgt: local/dict/silence_phones.txt}
    spk2gender: spk2gender
    utt2spk: utt2spk
    wav2scp: wav.scp
  word: [zero, one, two, three, four, five, six, seven, eight, nine]
egs:
  root: /work/kaldi/egs/digits
